### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by arslonga-vitabrevis** [arslonga-vitabrevis/furima-28861#10]
フリーマーケットアプリの挙動確認をお願いします。
## URL
https://furima-28861.herokuapp.com/
## Basic認証
- ID
myfurimaapp
- Password
0903
## 出品者用のログイン情報(テストさん)
- メールアドレス
tester@example.com
- パスワード
a123456
## 購入者用のログイン情報(furima太郎)
- メールアドレス
example@example.com
- パスワード
a123456
## 購入用テストカード
- 番号
4242424242424242
- 期限(m/y)
3/24
- セキュリティコード
123

**Comment by Toshihide-Kido-0106** [comment]
岡橋さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・新規登録
　パスワードは英数字だけ、数字だけでも登録できる
・出品ページ
　着払い商品で出品しても、価格すぐ下の表示が「送料込み」として表示される。
　（編集しても同じく「送料込み」になる）

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tomohumi1109** [comment]
岡橋さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
